# Generated by Django 3.2.4 on 2021-10-03 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20210930_2310'),
    ]

    operations = [
        migrations.CreateModel(
            name='facultys',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cname', models.CharField(max_length=200)),
                ('cpic', models.ImageField(default='', upload_to='static/facultys/')),
                ('ccourse', models.DateField()),
            ],
        ),
    ]
