# Generated by Django 3.2.4 on 2021-10-04 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_facultys'),
    ]

    operations = [
        migrations.CreateModel(
            name='faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cname', models.CharField(max_length=200)),
                ('ccourse', models.CharField(max_length=100)),
                ('cpic', models.ImageField(default='', upload_to='static/facultys/')),
            ],
        ),
        migrations.DeleteModel(
            name='facultys',
        ),
    ]
