# Generated by Django 3.2.4 on 2021-10-04 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20211004_1626'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='faculty',
            new_name='fact',
        ),
    ]
